name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --no-save
      - run: git describe --tags
      - run: npm --no-git-tag-version version $(git describe --tags)
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Setup .npmrc file to publish to GitHub Packages
      # - uses: actions/setup-node@v1
      # with:
      # node-version: '10.x'
      # registry-url: 'https://npm.pkg.github.com'
      # scope: '@kamaz' # Defaults to the user or organization that owns the workflow file
      # Publish to GitHub Packages
      # - run: npm publish
      # env:
      # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
